### PR TITLE
Add language: Polish

### PR DESCRIPTION
**Pull request by lwojcik**
Done. :) :poland:

### CODE REVIEW

**Comment by ksylor** [comment]
Thank you so much for this! I'm sorry that it took me a bit to respond, turns out my github notification emails weren't set up properly :D

**Comment by lwojcik** [comment]
No worries, glad to help. :)

**Comment by ksylor** [comment]
@lwojcik PM me your address on twitter and I’ll mail you a packet of stickers!

**Comment by lwojcik** [comment]
Yay, thanks! Shooting a DM now. I'm that guy with a pixel art avatar on a blue background.

**Pull request merged**
