### PR TITLE
Add vietnamese translation

### PR DESCRIPTION
**Pull request by japananh**
Hi, I've translated the site into the Vietnamese language. Please let me know if you find any mistakes. I'll fix them.

Thanks for the great content and the slang. Some of them are hilarious. I shared your site with my team.

### CODE REVIEW

**Comment by Meigyoku-Thmn** [comment]
There are 2 versions of ohshitgit, a swear version and a non-swear version. It seems that you only translated one.

**Comment by japananh** [comment]
> There are 2 versions of ohshitgit, a swear version and a no-swear version. It seems that you only translated one version.

@Meigyoku-Thmn To be honest, I know a few Vietnamese swears, so I'm not confident to use them here. "Chết tiệt" (oh shit) is the "swear" that I think is appropriate to the context. If you know other great swears, feel free to comment here or create a PR.

**Comment by Meigyoku-Thmn** [comment]
I has made a PR since April https://github.com/ksylor/ohshitgit/pull/103

**Comment by japananh** [comment]
> I have made a PR since April #103

@Meigyoku-Thmn Oh, I didn't notice it. I read your translation. It sounds more natural than mine. Great jobs. I'll close my PR.

**Pull request closed without merging**
