### PR TITLE
Add Swedish translation

### PR DESCRIPTION
**Pull request by cybear**
Swedish translation.

I've thought about the phrasing and wording for a while and I think the translation is good.

I think that I've added the correct settings for importing the Swedish language into the site as well. It works on my local machine at least.

### CODE REVIEW

**Comment by ksylor** [comment]
Hey Ryan, This all looks great! 

I'm curious to better understand why "Shit French Fries" is the right translation for "Oh, Shit" in Swedish? Would keeping it as "Oh, Shit" work? Or is shit only used in combination with french fries lol?

**Comment by cybear** [comment]
This is a humorous minced oath in Swedish which are something most people recognize as a funny expression.

**Comment by cybear** [comment]
I'm open to changing it but I'll need to think about it because we don't say "oh shit" in Swedish.

**Comment by ksylor** [comment]
If you think it's the right way to go and will be funny to Swedish speakers, then I totally defer to you. It's just a very strange expression in English!! lol

**Comment by ksylor** [comment]
Thanks so much!!

**Comment by cybear** [comment]
No, thank YOU Katie! :)

**Pull request merged**
