### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by tpaksu**
I translated the Turkish version of both "dangitgit" & "ohshitgit". Hope it helps.

### CODE REVIEW

**Comment by tpaksu** [comment]
@ksylor ?

**Comment by ksylor** [comment]
Hey Taha, I'm really swamped right now working extra hours trying to manage
a bunch of big projects at my full time job and also homeschool and
teaching my two young children due to COVID school closures. I'll try to
get to this over the weekend. Thanks!

**Comment by tpaksu** [comment]
Hi Katie, no problem, I saw your reaction on the post we talked about ohshitgit on twitter, so I just wanted to take your attention here :) Good luck with the kids. Hope everything is well. Bests.

**Comment by ksylor** [comment]
Hey Taha! I took a look and everything looks great! 

I noticed that on the swears version, you seem to switch between using `Hasktir` `Hassktir` and `Sktir` to replace `Oh Shit`? Is that typos or on purpose? I'd prefer to use the same words repeated on each section description, unless there's a grammatical reason for switching. Thanks!

**Comment by tpaksu** [comment]
Yes they emphasize the mixed feelings. Like "shiiiit" with some worry mixed, and "shit!" with exclamation and anger (perhaps).

**Review by ksylor — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
